### ISSUE TITLE
User and label list for Label-bot access on monero-site repo 

### ISSUE THREAD

**Issue by danrmiller** [monero-project/meta#103]
Which labels need to be used for the monero-site repo?

Which users should be allowed to label and close issues?

**Comment by anonimal** [comment]
Does [this list](https://github.com/monero-project/meta/issues/62#issuecomment-313512337) still apply? If so, should we PR the list for easy reference?

**Comment by anonimal** [comment]
Opened https://github.com/monero-project/meta/issues/119.

**Comment by QuickBASIC** [comment]
>Which labels need to be used for the monero-site repo?

@danrmiller 

```
bug
feature
improvement
question
critical
important
low priority
in progress
resolved
duplicate
wontfix

merchant
merchant removal
guide
blog
moneropedia
wrong repo
grammar
discussion
```
* see: monero-project/monero-site#401 for example of something we `wontfix`, (identified scam site) so maintainer can identify and close these.
* `merchant`s currently open 1 issue per request. It would be helpful so they could be identified quickly
* Some users are comfortable creating `guide`s, but don't know how to add them to the user guide landing page (It's mostly HTML and kind of intimidating for new users). This would enable a contributor to identify guides that can be created and imported into the site. This also can be used requests for guides to be written.
* Many users will open an issue for `merchant removal` (see monero-project/monero-site#283) generally we want to leave these open for a time so that others can comment on whether or not they agree with the assessment of the merchant being scammy before we remove it and we can mention the merchant if they're on github, so they can comment.
* Many `blog` posts and missives notes and transcriptions get dumped into issues until someone makes them a blog post. (see monero-project/monero-site#17)
* The `moneropedia` is still relatively sparse, many users make requests to create a moneropedia entry (see monero-project/monero-site#106). Contributors that feel equipped to can identify missing entries and write them.
* As big as the monero-project is many users open issues in the `wrong repo` (see monero-project/monero-site#109) and should probably should be closed immediately.
* Many users open issues to report `grammar` or spelling issues (see monero-project/monero-site#349 (these are probably going to be similar to `easy` on `monero-project/monero` repo.
* Sometimes there needs to be `discussion` on certain things that are being written for consistency and it's not always expedient for contributors to make a PR and they discuss the ramifications of the changes. (see monero-project/monero-site#165).

**Comment by danrmiller** [comment]
@anonimal wrote:
> Does [this list](https://github.com/monero-project/meta/issues/62#issuecomment-313512337) still apply? If so, should we PR the list for easy reference?

The list will always be the labels existing for the repo, in this case https://github.com/monero-project/monero-site/labels

@QuickBASIC Since there were no other comments, I will configure the labelbot to start checking the monero-site repo and get the labels you requested setup.

**Comment by QuickBASIC** [comment]
@danrmiller 

Awesome. Thank you. Do you know who is or is going to be tagged for permission to use the labels on the monero-site repo?

**Comment by danrmiller** [comment]
Oh good point. I won't activate the label bot for the monero-site repo until we know who will have permissions to tag and close issues.

**Comment by danrmiller** [comment]
Also, I am going to use "invalid" instead of "wrong repo" for consistency with the other projects.

**Comment by QuickBASIC** [comment]
> Also, I am going to use "invalid" instead of "wrong repo" for consistency with the other projects.

Roger, makes sense... Not a developer, so I didn't know what ones were being used on the other repos.

> Oh good point. I won't activate the label bot for the monero-site repo until we know who will have permissions to tag and close issues.

I don't know who everyone is, but the most active contributors over the last several months from what I see are:
@rehrar (4 PRs merged+ site redesign so it's a given he'd be included)
@bigreddmachine (6 PRs merged)
@dEBRUYNE-1 (20 PRs merged + he posts the meetings, so it's probably a given he'd be included.)
@SamsungGalaxyPlayer (10 PRs merged)
@mattcode55 (12 PRs merged)
@erciccione (5 PRs merged)
@QuickBASIC (10 PRs merged)
@anonimal (10 PRs merged)
@MaxXor (2 PRs merged, but is active in reviewing other PRs and posting comments in issues)
@tyrionmcmaster (6 PRs merged) 
@qertoip (6 PRs merged)
@jonathancross (5 PRs merged)

I'm sure there are better metrics than merged PRs, but these are all people that are active in maintaining the site and comment on issues and review PRs, that I've seen. Obviously should include core developers, etc. If I've excluded anyone, it's certainly not on purpose, these are just my observations.

Special mention: @erciccione and @mattcode55 are always some of the first to answer issues on the monero-site repo or review PRs. I wouldn't mind being included as well.

I'm not certain that I'd expect whole list to have access to the label-bot, but I believe most of these people would be interested in that discussion, so I've tagged them.

**Comment by rehrar** [comment]
Yeah, I'd be down if community agrees.

**Comment by erciccione** [comment]
Thanks for the mention @QuickBASIC , happy to do it if needed

**Comment by jonathancross** [comment]
ACK

**Comment by QuickBASIC** [comment]
@danrmiller 

It's been 7 days since I tagged the most frequent contributors to the monero-site repo and also created an issue there to link to this discussion. Since there doesn't seem to be anyone adding any further information or acknowledging the mentions, I propose we move forward by assigning permission to those who have acknowledged interest (and any core contributors you feel is appropriate) and activate the label bot.

@rehrar 
@erciccione 
@jonathancross 
@mattcode55
@QuickBASIC

**Comment by danrmiller** [comment]
Done. I don't follow the -site repo so let me know here or on irc (pigeons) if it doesn't work.

**Comment by QuickBASIC** [comment]
Awesome. Thank you. Tried to label monero-project/monero-site#441 doesn't seem to be working atm.

**Comment by erciccione** [comment]
same for me monero-project/monero-site#449

**Comment by danrmiller** [comment]
OK, I need to handle temporary 412 errors from gitlab api, should be fine for now

**Comment by mattcode55** [comment]
For something like monero-project/monero-site#401, should `+wontfix` close the issue?

**Comment by QuickBASIC** [comment]
I'm also wondering if `stale` should close an issue too since it's not `resolved` nor `wontfix`. We probably don't want to keep those issues open forever if the OP isn't responding or providing needed information.

**Comment by mattcode55** [comment]
Ping @danrmiller

**Comment by danrmiller** [comment]
wontfix and stale will now close the issue. Let me know if there is anything else.

**Comment by erciccione** [comment]
Now that the website is multilingual, would be good to have a `Localizations` label . Can you add it @danrmiller ?

**Comment by danrmiller** [comment]
The ```localizations``` label has been added to monero-site.

**Comment by jonathancross** [comment]
@danrmiller Thanks for setting this up!  I tested and works well.
Is this going to be setup for `monero-gui` repo as well?  Would be very useful there.

**Comment by erciccione** [comment]
At this point, also for `monero` :)

**Comment by QuickBASIC** [comment]
@danrmiller 

Sir, when you get a chance can you look at monero-project/monero-site#635 and monero-project/monero-site#636. The bot doesn't seem to be closing the issues for wontfix or resolved.

**Comment by mattcode55** [comment]
It doesn't close issues tagged with `+invalid` either

**Comment by jonathancross** [comment]
FYI: I was able to successfully open https://github.com/monero-project/monero-site/issues/528 and then close it using `wontfix`.  There was a delay of several minutes, but it worked.

**Comment by plowsof** [comment]
can this be closed as completed @erciccione?

**Comment by erciccione** [comment]
@plowsof yeah definitley. The label bot doesn't even exist anymore iirc.
