### ISSUE TITLE
Kovri: DragonBSD build failing

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#130]
@danrmiller how did you build boost? https://build.getmonero.org/builders/kovri-all-dragonflybsd-amd64

**Comment by danrmiller** [comment]
I didn't build it, its DragonflyBSD's port of boost-libs-1.63.0_1

**Comment by anonimal** [comment]
Was clang needed for monero? I don't remember asking to switch to clang for dragonflybsd... The build started failing in-between the switch from gcc to clang:

- [Working gcc build](https://build.getmonero.org/builders/kovri-all-dragonflybsd-amd64/builds/218/steps/compile/logs/stdio)
- [Failing in-between switch](https://build.getmonero.org/builders/kovri-all-dragonflybsd-amd64/builds/219/steps/compile/logs/stdio)
- [Beginning of failing clang build](https://build.getmonero.org/builders/kovri-all-dragonflybsd-amd64/builds/229/steps/compile/logs/stdio)

**Comment by danrmiller** [comment]
It switched to clang because I thought all of the platform specific build environment differences were gone so I combined the BSDs to use one build factory. But I missed the difference that dragonfly doesn't use clang, or maybe figured it wouldn't matter.

I've switched back to gcc for dragonfly and it builds:

https://build.getmonero.org/builders/kovri-all-dragonflybsd-amd64/builds/342
