### ISSUE TITLE
Monero update caused my hardware break down

### ISSUE THREAD

**Issue by azerigid** [monero-project/meta#207]
Monero management urgent contact me about day by day growing problem regarding scam mining and scam updates took place from march to april, that caused breaking my expensive graphic cards and montherboards
Among that my minergate account was switched to different software which caused my hardware to disfunction and caused wasted electricity bill
1) I DEMAND   MONERO BLOCKS ACCESS, WERE STOLEN FROM ME , BLOCKS FOR ALL 5 MILLION GOOD SHARES I HAD
2) AMOUNT OF 2000 USD AS COMPENSATION FOR BROKEN HARDWARE CAUSED BY SOFTWARE UPDATE DONE WITHOUT MY KNOWLEDGE AND AGREEMENT, TOOK PLACE  FROM MARCH TO APRIL  and wasted electricity bill for the last 4 months was over 500 usd
If no measurements taken i might do everything LEGALLY to bury this token during this and next month
My email address: dogovornyaga@gmail.com

**Comment by rehrar** [comment]
I'm sorry, demand from who exactly?

**Comment by luigi1111** [comment]
The hardfork occurred on April 6, only 11 or so days ago, not 4 months.

...but it's all irrelevant anyway.

Open an issue with Minergate, where you were presumably mining and where you likely got the mining software in the first place.

**Comment by azerigid** [comment]
You are creating chaos this way, you cant change the software while users
mine the old one, if you decided to do so, you have to inform all miners by
emails about such matter. Jurisdically if you promised mining wirh block
rewards its a crime to block users who have 5 million good shares to access
block rewards and moreover its illegal to shut down the older version, my
electricity wasted bill is over 200 USD, if you all continue ignoring
Monero as cryptocurrency will stop its existance, i can promise it from my
side, i will do everything to bury your project

**Comment by rehrar** [comment]
K

**Comment by anonimal** [comment]
>AMOUNT OF 2000 USD AS COMPENSATION
>wasted electricity bill for the last 4 months was over 500 usd
>my electricity wasted bill is over 200 USD
>i might do everything LEGALLY
>i can promise it from my side, i will do everything to bury your project

@azerigid What shithole country do you live in - in which a lawyer will charge less than $2200 to pursue a frivolous, unrelated "damages" lawsuit to collect $2200? Also, 4 months of mining for only $500 electricity?!?! Sign me up.

**Comment by azerigid** [comment]
Minergate doesnt reply anymore, they say Monero dev team is responsible,
not them

**Comment by fluffypony** [comment]
@azerigid and you believed them?

**Comment by mattcode55** [comment]
@azerigid What was the damage done to your motherboards and graphics cards? Maybe somebody here will help if you ask nicely :)

**Comment by el00ruobuob** [comment]
@azerigid Minergate are scammers. You should know that. Btw if you try to inform from several sources, like getmonero.org and Twitter you will have know those two facts: Minergate is scamming people and monero has a 6 month regular network upgrade.
Get a closer look at monerominer subredit and ask for help for your hardware over here, or on stackexchange (again you'll find direct links on getmonero.org)

**Comment by azerigid** [comment]
to: mattcode55 if you provide email address i can show you photos of all
evidences
graphic cards mined in error, the new software coding is different , both
graphic cards are 4 month old, ASUS RX580 and ASUS R9390, their 8gb  memory
isnt working, dead
Asus couldnt fix them, they claimed graphic card had multiple error
interference
My problem isnt only here i had 5 million shares and they never granted me
access to any of blocks i found, untill today i have only 0.33 xmr balance
for all these 3 years
its very low type attitude, whoever is involved here is extremely greedy,
got 95 % of all earnings and even destroyed my expensive hardware, total
nonsense!!!

**Comment by curumimxara** [comment]
Hello @azerigid, I understand your frustration. It's a very bad thing that happened to you, really. I'm also a miner and I intimately know all the frustrations and expenses that we have running such operation like yourself. Unfortunately you're complaining in the wrong place and with the wrong people.

You have to understand that the Monero protocol and network to not discriminate hashes. If you were solo mining, then all your hashes would be considered and in case you were responsible for solving a block you would get the whole reward. This is how the protocol is written, there's no way to avoid that.

Since it's very hard to solo mine with small mining rigs and farms, people started creating mining pools -- one example is MinerGate. What you have to understand here is that when you mine in a pool you send your shares / hashes to this company, called MinerGate, and the company sends the hashes to the Monero network. When MinerGate solves a block, the Monero network gives the reward to MinerGate, which in consequence should distribute it to its miners, giving the proportional amount based on the has power of each miner.

So, unless you were solo mining, you're complaining to the wrong people. The Monero protocol and network has absolutely nothing to do with MinerGate sending you your part of the reward.

Monero's website had multiple alerts telling that the change was coming. See, the Monero network doesn't keep "e-mails" from miners because it doesn't know what an e-mail is. Do you know who has this information? MinerGate. So this company had an obligation to warn all the miners about the change (after all, you're mining in their pool!) and they didn't. If there's someone who you should sue is MinerGate. If what you're telling is true and you really lost all these things, they it's a very big negligence in their part. There are many other mining pools out there who did an incredible job warning their miners about the upgrade.

If you want to make things right, try to find other miners from MinerGate with the same problem and start a class action lawsuit against MinerGate for their immense negligence on this very important matter.

I wish you good luck,
curumimxara.

**Comment by mattcode55** [comment]
>to: mattcode55 if you provide email address i can show you photos of all evidences

You can just attach them to a comment on this GitHub issue.

>Asus couldnt fix them, they claimed graphic card had multiple error interference

Can you also attach whatever emails ASUS has sent you?

>My problem isnt only here i had 5 million shares and they never granted me access to any of blocks i found, untill today i have only 0.33 xmr balance for all these 3 years

The number of shares doesn't really matter as they all have different values, but the reason for your low balance is that MinerGate skim your hashes. Compare the number of hashes sent as reported by your miner and as reported by MinerGate, you'll see a big difference

**Comment by ajs-xmr** [comment]
@azerigid https://github.com/monero-project/monero/blob/6f6521ad7a9832788e07f7f7d181ba29b010e311/LICENSE#L19

**Comment by azerigid** [comment]
so this update came from the air, you mean nobody invested money to create
this token, that there was no ico? that's ridiculous

**Comment by rehrar** [comment]
> so this update came from the air, you mean nobody invested money to create this token, that there was no ico? that's ridiculous

That's exactly what happened. There was a time before all the ICOs. I actually wasn't around during that time, and I assume you weren't either, so we're in the same boat. :D 

Need another example? Look no further than Bitcoin. There was no ICO, and there was no 'Foundation' or corporation that started it. Satoshi just launched it with a genesis block, and people who wanted to mine it and exchange it did so. Monero had a very similar beginning. No premine was taken, no ICO. Just a genesis block and a dream.

You see, the ICO people do things because they want money. They want to use cryptocurrencies like the new Kickstarter. Raise money to make products (or in many cases, they don't actually make anything). Projects like Monero and Bitcoin are made out of a desire also, but not to make money. The desire is to change the world. Monero wants to give everyone a private and fungible currency.

I'm more than happy to sit down and explain Monero's history, vision, and all of the other super neat projects that we have going on within it. Let me know if you'd be interested. :)

**Comment by azerigid** [comment]
if so, then there is nothing to worry about. We will contact interpol shut
down it as the currency and the owner will pop out right away. So next time
there will be no cheated worldwide users, and no new versions of it done
 by ghosts.

**Comment by rehrar** [comment]
Let me try to make this clear for you. 

There is no owner. There is no owner. There is no owner. There is a community that maintains and updates software. I've tried being patient with you, but it's obvious you're not understanding anything so this will be my last response. 

Please, go ahead and try to shut down Monero. I'll be sending you an email in six months to ask why you have failed. Best of luck.

**Comment by azerigid** [comment]
if so, it will be closed down
the currency that has no owner can not last for too long. if there are
illegal updates while users worldwide mining there supposed to be a person
involved who can take full responsibility
i think you are a boy, not even an adult , chatting with you is a waste of
time

**Comment by landergate** [comment]
@azerigid 
What exactly you mean by "illegal updates"? If you've missed a major update and didn't read any news or don't follow any activity around Monero project, that only means that you'll have to do better next time.

There is absolutely no reason to act so aggresively just because you've missed an update all by yourself and your pool. People here explained to you in details what exactly happens. Monero is not an another shitcoin with CEO who can send you monz from his premine, that's exactly why Monero is more valuable from the core than any shitcoin known by you by so far.

**Comment by azerigid** [comment]
you must be nuts if you talk this way. WHEN I DOWNLOAD YOUR MINING
SOFTWARE, I CONNECT MY PC TO THAT SOFTWARE AND START RUNNING, STARTING FROM
THAT SECOND YOU ARE RESPIONSIBLE FOR YOUR SOFTWARE.
YOU CANT CHANGE IT WITHOUT CONFIRMATION FROM USERS, THAT THEY KNOW AND
ACCEPT YOUR UPDATE, BECAUSE AMONG SOFTWARE THERE MILLIONS OF USERS
HARDWARES INVOLVED.
IF FOR EXAMPLE GOVERNMENT CHANGES VOLTAGE TO YOUR APARTMENTS AND INSTEAD OF
220VOLTS YOU GET 380VOLTS THAT GOVERNMENT MUST BE SUED.
DONT BE NUTS
I DOWNLOADED IT ONCE AND RUN IT 24/7, I PERSONALLY DONT HAVE TIME TO HANG
OUT AT ANY WEB SITES, WE HAVE WORK TO DO, BUT IF YOU CHANGE THE SOFTWARE
BOTH PARTIES ORIGINALLY AGREED TOO YOU NEED CONFIRMATION FROM USERS THE
THEY ACKNOWLEDGED ABOUT CHANGES AND WELL PREPARED.
WE DONT LIVE IN THE JUNGLE AND DONT TRY TO RECREATE JUNGLE RULES HERE
MINERGATE SAYS THEY SENT EMAIL TO VIP USERS WHICH AUTOMATICALLY MAKES THEM
DISCRIMITATORS AND THEY WILL TAKE FULL RESPONSIBILITY
HOWEVER THE ROOTS ARE FROM THOSE WHO DID THIS ILLEGAL UPDATES, UPDATES WERE
DONE FOR A GREED PURPOSE TO BLOCK ASIC MINERS FROM MINING MONERO. AND
BECAUSE OF THAT GREED I CAN EASILY FIGURE OUT THAT MY CASE IS NOT DIFFERENT
EITHER 5MILLION GOOD SHARES AND I STILL NOT GRANTED WITH EVEN A SINGLE
BLOCK, WASTED MY ELECTRICITY AND CHEATED MY EARNINGS
MONERO WILL BE CLOSED AMONG WITH MINERGATE

**Comment by anonimal** [comment]
@azerigid 

https://www.mayoclinic.org/healthy-lifestyle/adult-health/in-depth/denial/art-20047926
https://www.verywellmind.com/defense-mechanisms-2795960
http://www.minddisorders.com/Del-Fi/Denial.html
https://drsanity.blogspot.com/2006/04/strategies-for-dealing-with-denial_17.html
https://psychcentral.com/lib/are-you-in-denial/
https://www.psychologytoday.com/us/blog/insight-is-2020/201304/understanding-the-sociopath-cause-motivation-relationship
https://en.wikipedia.org/wiki/Denial
https://www.psychologytoday.com/us/blog/communication-success/201401/how-spot-and-deal-passive-aggressive-people
https://en.wikipedia.org/wiki/Cognitive_dissonance

**Comment by cryptochangements34** [comment]
Dude read the [LICENSE](https://github.com/monero-project/monero/blob/master/LICENSE). It says pretty clearly in all caps 

> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

If you weren't comfortable with using software that is provided "as is" then you shouldn't have used it

**Comment by rehrar** [comment]
I think there's a misunderstanding here. @azerigid may be thinking that the mining software itself changed after he had installed it on his computer. In the theoretical instance where it did change and install updates without his express permission, then yes, it would be basically malware and illegal. If he is indeed looking at things this way, then it would make sense that just because a bunch of people agreed to upgrade, doesn't mean the software he agreed to by putting on his machine should upgrade automatically. That's tyranny.

But we know that his software didn't change. The software on everyone else's computers changed for the network upgrade, and he didn't upgrade. Hence he is not participating with us.

That's the only explanation I could think as to how he's looking at this. Otherwise, I'm completely at a loss. :D

**Comment by azerigid** [comment]
my software was changed
i have proof that software switched from one version to another one
at old on i had 5 million shares it went offline
new one has different logo also
no way to mess around , all well documented

**Comment by azerigid** [comment]
well you are just a spoiled bad kid which needs father's belt , i guess you
are abnormal, maybe you have some brain disorder, maybe you mom dropped
you  couple of times when you was a little baby, however i think your
brain  not much changed since, and very likely you will be chardged for all
you illegal activities regarding your decentralized xmr updates, lol!

**Comment by Eatmylol** [comment]
You are living in a parallel world

**Comment by h355t0ph3r** [comment]
https://media.giphy.com/media/E3xXqq617AaFW/giphy.gif

**Comment by azerigid** [comment]
i'm healthy serious businessman, and every business i do well planned and
calculated. IF ANYBODY FROM OUTSIDE MAKES UNEXPECTED CHANGES AND CAUSES MY
PLANS TO FAIL, I BRING THAT INDIVIDUAL TO JUSTICE, SO THOSE WILL BE CHARGED
AND SEND TO PRISON, ONLY THEN YOUR PARENTS CAN COME OVER AND WE CAN HAVE
SOME TALK

**Comment by Eatmylol** [comment]
Well, let me tell you that in my opinion you are quite a stupid 'businessman'.

**Comment by kloinka** [comment]
I'm confused yet amused.
https://i.imgur.com/X5FhMpx.png

**Comment by h355t0ph3r** [comment]
azerigid,

Sorry to tell you this, it was well publicized that the software change was coming. https://www.newsbtc.com/2018/03/01/monero-hard-forks-to-monerov-in-mid-march/

Also, the block chain software change did nothing to your hardware-- it doesn't work like that.  you hardware simply stopped mining the blockchain that was supported by monero.  If it continued mining, it did so because Minergate changed it to a new coin (which you claim).

Lastly, your lost shares are mining profits you didn't realize on the pool you mined on (Minergate) not the blockchain.  So that is yet another minergate issue.

The only ground you would have to take action against the blockchain (which is impossible anyway) would be a loss in revenue due to the change-- but that isn't possible because there is no entity responsible AND the change was publicized.   In your example of the government changing voltage it would be similar if they ran news articles to make the public aware, you didn't pay attention and then your appliances burnt.  It is your fault for not paying attention.

---=== TO BE CLEAR ===---
the software change can in NO WAY damage your hardware.  Even if it could, the license agreement in the software absolves everyone of any claims.

Get a lawyer, they will tell you the same thing once your check clears.

**Comment by azerigid** [comment]
WELL LET SEE, WHEN FIND OUT ALL ILLEGAL XMR RELATED ACTIVITIES YOU ALL
INVOLVED , THEN YOU WILL SING DIFFERENT SONG, SONG OF TEARS!
I DID MY PART DESCRIBED YOU THE PROBLEM ASKED FOR SOLUTION  AND INSTEAD
SOLUTION WAS IGNORED SAME AS MINERGATE.
SO AFTE A WEEK THERE WILL BE MUCH MORE SOPHISTICATED PEOPLE INVOLVED, DONT
ASK ME FOR HELP THEN, DOORS ARE CLOSING
MY PERSONAL ADVICE TO YOU KIDS:
NEVER STEP ON LIONS TAIL ....
I GUESS YOU KNOW WHAT GOTTA HAPPEN

**Comment by Eatmylol** [comment]
We can set-up a donation fund for your illness.

**Comment by azerigid** [comment]
YOU ARE TALKING NONSENSE
IT DOESNT WORK THAT WAY
IF YOU WANT TO CHANGE THE SOFTWARE
THE RIGHT WAY IS:
DEAR USERS, PLEASE INSTALL NEW VERSION OF MINERGATE, THE OLD ONE WILL STOP
FUNCTIONING FROM MARCH 1ST 2018"

WHICH WAS NOT THE CASE, THEY SIMPLY SWITCHED IT, I NEVER RECEIVED ANY EMAIL
ABOUT NECESSARY CHANGES OR UPDATES
AND MINERGATE EVEN SAYS THEY INFORMED BY EMAIL, BUT ONLY VIP USERS WHICH
MAKES THEM MORE DISCRIMNATORY , AND GUILTY

**Comment by h355t0ph3r** [comment]
> MINERGATE EVEN SAYS THEY INFORMED BY EMAIL, BUT ONLY VIP USERS WHICH
MAKES THEM MORE DISCRIMNATORY , AND GUILTY

Then focus on them and for the love of god, stop typing in all caps.  It is the internet equivalent of SCREAMING.

**Comment by azerigid** [comment]
FOR DONATIONS YOU MIGHT NEED THEM IN NEAR FUTURE, MY CASE IS VERY CLEAR I
DEMAND THE AMOUNT RELATED TO UNEXPECTED LOSS CAUSE BY EXTERNAL PARTIES
WHICH IS XMR DEV AND MINERGATE

**Comment by ALLRiPPED** [comment]
You're a "Special" kinda stupid aren't ya?

**Comment by azerigid** [comment]
FUNNY YOU ARE A QUEEN OF IGNORANCE
I THINK YOU KNOW ITS NOT YOUR BUSINESS HOW I TYPE AND WHAT I TYPE
YOU REMIND ME A RUSSIAN JOKE OF SOLDIER IN THE ARMY
EVERYBODYALL TROOPS  LINED UP AND LEUTENANT COMES OVER TO CHECK THEM , THEN
SEES ONE OF THEM NOT WEARING A HAT AND ASKS HIM WHERE IS YOUR HAT? AND
SLAPS HIS FACE
NEXT DAY THAT SOLDIER WEARS A HAT AND WHEN LEUTENANT CHECKS THAT SOLDIER
AMONG OTHERS SEES HE'S WEARING A HAT, SIMPLY SAY: WHY DO YOU WEAR A HAT?
AND SLAPS HIS FACE AGAIN

BE REASONABLE , CALCULATE EVERYTHING BEFORE CLAIMING ANYTHING
OTHERWISE YOUR TALK HAS NO WEIGHT, EVERY SINGLE WORD MUST WEIGH AT LEAST A
KILO, I HAVE NO TIME FOR ALL THIS KIDS BULLSHIT

**Comment by azerigid** [comment]
INTEAD OF INSULTING ME I ADVICE YOU TO FIND THE SOLUTION , NOT MUCH TIME
LEFT
THERE ONLY 3 SOLUTIONS AT MAX
MY MINERGATE ACCOUNT: DOGOVORNYAGA@GMAIL.COM
1) PROVIDE ACCESS TO AT LEAST 3 MONERO BLOCKS AT MY MINERGATE ACCOUNT
2) CONTACT MINERGATE AND PAY ME AT LEAST 10 MONEROS AS THE COMPENSATION
3) PAY FOR MY ELECRICITY BILLS 500 USD + SEND ME NEW COMPUTERS WITH 2 NEW
GRAPHIC CARDS ASUS AMD R9 390 AND RX580
REGARDS
FM

**Comment by rehrar** [comment]
No.

**Comment by hypeboard** [comment]
So I went to go look at the minergate website to see if I could find if they posted an update about the network upgrade and even as shady as minergate can be they did post an update

https://minergate.com/blog/monero-original-on-minergate/
and here
https://minergate.com/blog/minergate-supports-monero-network-upgrade/

Also Not only was the update posted on the main monero website many Crypto news outlets also reported about the network upgrade. 

The software you were using was MINERGATE's software and had nothing to do with Monero . Your issue is with them and them alone but you have no case even with them due to the fact they did announce the update and told everyone to upgrade their software to keep mining Monero (XMR).

**Comment by azerigid** [comment]
THEN REGRET THIS FRIDAY I WILL CONNECT TO INTERPOL

**Comment by azerigid** [comment]
REMEMBER COLLECT ALL YOU REST OF ACTIVE BRAIN CAPABILITIES AND SOLVE IT
BFORE FRIDAY
IT MIGHT BE A GOOD IDEA TO SPLIT 50 /50 WITH MINERGATE
I DONT CARE HOW, I ONLY CARE ABOUT THE AMOUNT MUST BE EXACT SAME TO COVER
MY LOSSES
I SAID EVERYTHING IN RESPECTFUL WAY, NO HUMILIATION WHATSOEVER
WARNED YOU ABOUT EVERYTHING, SO DONT BLAME ME WHEN THINGS BECOME MORE
COMPLICATED
I WONT BE ABLE TO SOLVE DURING THAT TIME
DO IT NOW OR REGRET TOMORROW WITH SLEEPLESS NIGHTS

**Comment by rehrar** [comment]
kthxbai

**Comment by Eatmylol** [comment]
I'm already taking sleeping pills.

**Comment by kloinka** [comment]
Aze the Rigid has spoken!

**Comment by azerigid** [comment]
ITS TIME TO BUST ALL THIS GANG TO WHERE THEY BELONG TO

**Comment by el00ruobuob** [comment]
@azerigid do you realize we where trying to help you? Gave you advices for where to get help about your hardware issue, tried to explain in many ways that monero network has regular upgrades on a 6 month basis which are well documented everywhere, told you that the community around monero network  is a non-profit one, that the mining software is not provided by monero community but Minergate (which are known scammers) and you continue yelling at us like that? That's nonsense. How in hell do you expect Interpol to even answer you? Class action against Minergate is your only chance, but according to the previous posts regarding their communication and the terms of use you should (as an advised businessman you claim being) have carefully read, they're not responsible for anything. By the way, it's a company from Hong Kong which put them in a position where sues are impossible.
Good luck to you, we do not risk anything for providing an open-source software as-is.

**Comment by el00ruobuob** [comment]
In the beginning it was funny. Now it is just sad.

**Comment by el00ruobuob** [comment]
@azerigid by the way Interpol might be interested it the way you promote beating child with your belt. Is it something you often do? Or do you have childhood harms you want to talk about?

**Comment by azerigid** [comment]
IN YOUR CASE BELT WILL NOT HELP, THERE IS NO CURE , NO TREATMENT FOR
MENTALLY NEGATIVELY SELF ORIENTED KID TYPE PEOPLE, BRAIN DIDNT GROW UP
CONDITION , WHAT CAN I DO FOR YOU, ASK YOUR DAD TO PUT ON ON THE RIGHT
PATH, HOW?

**Comment by azerigid** [comment]
TO YOU IN THE BEGINING WAS FUNNY BECAUSE YOU DONT GIVE A SHIT WAHT IS GOING
ON AROUND YOU MAKING FUN OF PEOPLE
THIS CASE IS DIFFERENT
THIS CASE WILL TEACH YOU ALL 1 LESSON
WHEN YOU EAT, LET OTHERS EAT TOO
5MLN SHARES WITH NO PROFIT?
YOU MUST BE NUTS IF YOU THINK WE PEOPLE GOTTA LET IT GO
I 'M NOT ALONE, THERE WILL BE DOZENS OF PEOPLE INVOLVE IN THIS LAWSUIT
AGAINST MONERO AND MINERGATE, HOWEVER IF YOU ARE HEALTHY NORMAL BEING
COLLECT ALL YOU NORMAL POSITIVE BRAIN CELLS TOGETHER COME TO CONCLUSION
WHAT TO DO RIGHT TO SOLVE THIS RIGHT NOW SMALL PROBLEM

**Comment by anonimal** [comment]
@azerigid Bro, your capslock is stuck.

**Comment by azerigid** [comment]
allright you said bro, i reply you same way
This problem can not persist
I'm against all negativity however, just think
3 -4 years of mining with no Block access ( i know i found several blocks
because of math calculations the price when i started to mine was less than
60 usd per 1 monero) so difficulty was low too
However 5mln good shares with no balance is not right
+ this software update where my computers were non stop mining with the
software they changed without my permition
when i set it, it was functioning, then they changed their mind about that
software and had no confirmation from me, i had no ideas they did something
like that
wasted my computers mining on the software that has different coding is
illegal
I needed to download that software before enabling new and replacing the
old version
1. unfair mining conditions and  unfair software practices
2 waste users electricity
3 user unfriendly update that caused hardware to malfunction
These are your problems , not mine, can not be mine i fully control my
businesses, i wouldnt alllow losses in the first place

**Comment by Eatmylol** [comment]
You are a brainless fucking idiot and you have no idea how mining works. I don't know what the fuck have you installed in your shitty ass computer to brick your GPUs but you are definitely BRAINDEAD. Go fucking away, you're a disease. Still complaining? Contact your fucking GPU supplier and ask for warranty covers you fucking idiot.

**Comment by anonimal** [comment]
>I don't know what the fuck have you installed in your shitty ass computer

This brings up a good question, not that the answer is in any way relevant to this thread: @azerigid where did you download the software from?

**Comment by azerigid** [comment]
HET WHAT ARE YOU TALKING ABOUT? TALK POLITELY... YOU ARE NOT FROM
COUNTRYSIDE ARE YOU?

**Comment by el00ruobuob** [comment]
@azerigid after all you're insulting the all of us since the beginning while we're trying to help. So @eatmylol just write out what you deserved to read.
Anyway you're not complaining to the good guys.

**Comment by el00ruobuob** [comment]
@azerigid did you got Interpol over the phone? You may also want to contact NSA MI5 and MOSSAD in the meantime.

**Comment by azerigid** [comment]
since the start i was very politely describing my problem, everythins
documented here, i printed out all your messages also. there is no mistake
that most of you being very rude, there some otherv eyes read your
corresponces too
so be professional what is your question now?

**Comment by el00ruobuob** [comment]
I have no questions. I'm a community member trying to help by redirecting you to the good places to ask.
Stackexchange for your hardware
Getmonero.org and Reddit/r/monero for keeping posted on news
Minergate class action for your lost (stolen by Minergate) shares.

**Comment by azerigid** [comment]
you was born as a cheap low idiot and you will dies as a loser, because you
talk like a loser

**Comment by el00ruobuob** [comment]
Still talking politely I see...

**Comment by azerigid** [comment]
well that was my answer

**Comment by mattcode55** [comment]
I still can't tell if you're a troll or not (if you are, you're a very
funny one).

But if you're not trolling: you still haven't explained what exactly
happened with your graphics cards and motherboard. Did they fail
catastrophically, filling your room with smoke and fragments of GPU
cooler? Does it just fail to boot now?

Also you're not listening to what people are saying. Yes, you were
scammed, but by MinerGate. Not by any of the people that help develop
Monero.

**Comment by azerigid** [comment]
i'm not troll and i advice you to be polite
i have feeling most of the people here are on kids on drugs. i'm at ur
dad's age 45 now so at least talk like a human being, not an asshole
the truth is 5 mln good shares and no single block rewarded, i'm here for
truth and i think the truth is monero owner is the one who scams the whole
world
there is no such thing as block here, because there is some colombian mafia
i think involved here and they dont let anybody to earn anything, they take
almost everything and give about 5 %
most of the people here at git hub are doing some serious drugs i guess,
according to the tone they have while chatting others, very unhealthy one,
a hundred punches to their ugly faces wouldnt be enough

graphic cards now
----------------------------
From March to april both computers with 8gb new asus r9 390 + rx580
altogether with motherboards went down
not turning on serious errors caused failure that what i ve heard at asus

for hole march computers ran in error because they were set to another
version of monero, the old one with 5mln shares wass offline, photos are
available

**Comment by fluffypony** [comment]
I draw the line at you accusing people of being kids on drugs.

A decentralised network cannot be held responsible for software you choose to run on your computers. Burning out your graphics cards has nothing to do with us, and has everything to do with you using them for mining, for which your hardware manufacturer is choosing not to honour the warranty.

Finally, if you haven't been paid by a mining pool like MinerGate, that is NEVER the problem of the decentralised network. You have a commercial arrangement with MinerGate, so deal with them.

This thread is now being locked to prevent you from mistreating those who are trying to help.
