### ISSUE TITLE
Buildbot: use appropriate clang binary name on armv7 machine

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#216]
>`/bin/sh: 1: clang++: not found`

https://build.getmonero.org/builders/kovri-static-ubuntu-arm7/builds/403/steps/compile/logs/stdio

**Comment by anonimal** [comment]
>make[1]: clang++: Command not found
>make[1]: *** [cryptlib.o] Error 127
>make: *** [release-static-deps] Error 2

Prevents the static build from completing.

**Comment by danrmiller** [comment]
Is it alright with you if we use gcc as we do for the shared lib build instead of clang for this job? I believe on reason we switched to clang on this platform was that the build was a little faster. I'd like to use ccache, and while clang is supposed to be able to work with ccache, I've been reading of several issues, and you can see the failed attempt here:

https://build.getmonero.org/builders/kovri-static-ubuntu-arm7/builds/405

Here is the successful ccache/gcc build:

https://build.getmonero.org/builders/kovri-static-ubuntu-arm7/builds/406

**Comment by anonimal** [comment]
Ok, looks fine to me.
