### ISSUE TITLE
Kovri Defcon meeting: Tuesday, June 26th, 2018, 20:00 UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#240]
### Location:
- [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com) | [Mattermost](https://mattermost.getmonero.org/)
  - `#kovri-dev`

### Time
- Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html) to see when the meeting is for you.

### Proposed meeting items:
1. Greetings
2. Table & Materials discussion
3. Presentation discussion
4. Logo discussion
5. Any additional meeting items
6. Confirm next meeting date/time

Notes:
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by anonimal** [comment]
This meeting me be canceled and instead merged with the next community defcon meeting.

**Comment by SamsungGalaxyPlayer** [comment]
I recommend merging with the general DefCon meeting, or tacking it on immediately after.

Do you still want to have it in `#kovri-dev`?

**Comment by sanecito** [comment]
@anonimal The Community Workgroup meeting is every two weeks. Because it was last week, and the DefCon is another one-weeker instead of going back to a two week cadence, they are now out of sync, so there should be nothing at 17UTC when the DefCon meeting would formally end this Saturday (assuming the agenda lasts until 17UTC)

**Comment by anonimal** [comment]
We had the meeting but will continue the discussion come Saturday (next defcon meeting).

**Comment by anonimal** [comment]
+resolved
