### ISSUE TITLE
Monero 3C Meeting: August 25th, 2018, 17:00 UTC

### ISSUE THREAD

**Issue by rehrar** [monero-project/meta#270]
This is just a housekeeping ticket. The agenda is not completely set, but if anybody has any suggestions on things that absolutely should be on this issue, please let me know.

**Comment by SamsungGalaxyPlayer** [comment]
This will happen on #monero-community.

**Comment by parasew** [comment]
Hi rehrar, Justin and everyone else!

I am suggesting the following agenda in order to discuss and plan the C3 accordingly

- Input on defcon and how things were going there
-- What went well?
-- What went wrong?
- What is CCC?
- Monero at C3: Brief info on historical development (from 2016, 2017)
- Detail on how 34C3 was implemented and planned
- Details and suggestions for the 35C3
-- Organisation
-- Program
-- Working groups
-- Other relevant things
- Pointing out the relevance of submitting talks for the main program (kovri, etc.)
- Suggestion: AFK meeting of community during HCPP in prague to plan further (https://neworder.hcpp.cz)
- FFS for production and implementation?

All the best, Matthias

**Comment by SamsungGalaxyPlayer** [comment]
It looks like the Matrix/Riot relay is down. Please use IRC directly.
