### ISSUE TITLE
Statement from Core Team on Rehrar

### ISSUE THREAD

**Issue by binaryFate** [monero-project/meta#583]
In 2017, the Core Team engaged Diego Salazar (“rehrar”), as a contractor, to pick up slack that no one else in the community was willing to do. Monero was a much smaller project back then, both in community size and in numbers of contributors.
He has been instrumental in helping to get so many projects going and also in providing behind-the-scenes support to many existing projects and volunteers. Projects that have benefited from rehrar’s work include, among others, the CCS, CakeWallet, Monerujo, The Monero Village at DefCon, and Monero’s presence at the Chaos Communication Congress. 

We want to acknowledge that several valid points were raised by the community, in particular around conflicts of interest, during the last year. The most recent was “[An open letter to the core team](https://www.reddit.com/r/Monero/comments/o0sura/an_open_letter_to_the_core_team/)”. This has led to the [resignation](https://www.reddit.com/r/Monero/comments/o322ds/resignation_plan/) of rehrar effective August 9, 2021.
However, on reflection over the course of this past week the Core Team has instead decided to terminate the contract with rehrar immediately (effective June 22th). We do recognize in hindsight that there were clear signals we could have been more sensitive to, that would have justified a much earlier termination of rehrar’s contract. This is something we will keep very closely in mind in the future.

In addition to the multiple conflict of interest concerns raised by the community, we uncovered the following after “[An open letter to the core team](https://www.reddit.com/r/Monero/comments/o0sura/an_open_letter_to_the_core_team/)”:

https://ccs.firo.org/ ; https://github.com/firoorg/ccs-front/commit/be8182327acb8bf7c693c0c5e28a10730f0480f0 ; https://github.com/firoorg/ccs-back/commit/70b766b9b887401eb7df6c617b6f645fdeb710bb
We note that the initial commits were made on December 16th, 2019. We invite the community to make their own investigations and conclusions regarding the copyright infringement of the content and code in the Monero CCS front and back end, as a result of these Firo commits. 

A part of rehrar's role was to keep his finger on the pulse of the community and the project, aiming to know and report to the Core Team anything that might be of interest or concern to the Monero project at large. We note that at the end of December 2019, during the 36C3 congress in Leipzig, Germany, rehrar had the opportunity to speak in person with three members of the Core Team, and no mention was made regarding the Firo commits. Unfortunately, we feel that a similar pattern occurred with many of the community concerns where a proactive approach of bringing all these facts to us in a prompt and clear manner was not taken. The culminating example of this was rehrar securing a one year, full-time contract for sarang with another project, which we only discovered very recently. We consider this pattern to have been a breach of trust, and a direct contradiction with rehrar’s role.

   
Note: the Core Team's role, relative to the project, is quite limited nowadays, and currently consists of three components where unfortunately centralization cannot as yet be avoided. These include: gate-keeping write access to the "official" Monero repositories; controlling the "main" Monero domains and web servers; administering and dispensing donations via the General Donation Fund and the Community Crowdfunding System (CCS). We generally strive to become as irrelevant as possible to the well being of the Monero project.

**Comment by SamPorter1984** [comment]
So after this sorted, I will repeat again what I said in discord and in irc:

Your best option is to get me on board as a community manager, except I do not ask for money.
I have created of the most advanced god protocol to date, which makes cryptocurrency it supports unbannable, and if it supports proper privacy coins like Monero, it means it makes probably any cryptocurrency unbannable. More than that, since Aletheo is about influencing society, it can even lead to legalization of XMR.

The protocol however is blockchain-agnostic, so it starts on Ethereum, because it makes sense to start there.
So in exchange I don't need much, only a bit of recognition from XMR community, because I believe that privacy is a human right, and people who believe that too must also know about that. However, it does not mean that I will shill Aletheo to XMR community in fact, if you are probably strictly against that, I can even deny it's existence as joke, and never mention it. The reason is simple: aletheo main utility is shilling itself anyway, so me being able to talk about aletheo with xmr community is not something that is critically required.

So yeah, let's do it. I can be a community manager of sorts, just not too active. So we full wh40k now, you will either join decentralized emperor of mankind or else you will join later
