### ISSUE TITLE
Community Workgroup Meeting: Saturday 11th December 2021 17:00 UTC

### ISSUE THREAD

**Issue by michaesc** [monero-project/meta#638]
### Meeting location

[Libera](https://web.libera.chat/)|[Matrix](https://matrix.to/#/#monero-community:monero.social?via=matrix.org&via=monero.social)
* #monero-community

### Meeting date

Saturday 11st December 2021 17:00 UTC

Use the [timezone converter](https://www.timeanddate.com/worldclock/converter.html) to see when the meeting is for you.

### Moderation
* Keiji

### Meeting Items
1. Greetings
1. Week review
1. CCS reports
   * Status reports
   * New proposals
1. Web sitemap report
1. Open discussion
   * Outreach
   * Translation
   * Hardware
   * Tari
   * MRL
   * Whatever
1. Conclusion

**Comment by moneroguides** [comment]
hiya, I would like to add an item of discussion to the upcoming meeting; issue 1900 from the monero-site repo - https://github.com/monero-project/monero-site/issues/1900

**Comment by michaesc** [comment]
> I would like to add an item ... monero-project/monero-site#1900
>
The ticket refers to a sitemap reorganisation, so I made a entry for that in the agenda between CCS and Open ideas. I can't wait to learn something new aboutour website, thanks.

**Comment by carrington1859** [comment]
17:00:12 <Keiji[m]_ https://github.com/monero-project/meta/issues/638
17:00:17 <carrington[m]_ Hello and welcome to a Monero community meeting! These meetings are a chance for updates on recent events in Monero, as well as focussed discussion on crowd funding proposals. Please try and stick to the agenda, as there will hopefully be time at the end for any other business.
17:00:20 <Keiji[m]_ 1. Greetings
17:00:40 <msvb-lab_ Hello.
17:00:44 <carrington[m]_ Hi hello howareya
17:00:47 <Rucknium[m]_ Present :)
17:00:55 <midipoet_ hi
17:00:56 <rottenstonks_ Greetings.
17:01:18 <netrik182_ Hi
17:01:47 <elizabeth[m]_ hey :) 
17:02:17 <carrington[m]_ As far as updates for the past week or so:... (full message at https://libera.ems.host/_matrix/media/r0/download/libera.chat/fceb60578176191a0bf8169ded70db12652a0bf0)
17:03:26 <msvb-lab_ Wow the new Haveno site looks very good, is the author here?
17:03:34 <msvb-lab_ https://haveno.exchange/
17:03:42 <netrik182_ About the point release. We had plenty of languages updated in GUI as well
17:03:49 <rottenstonks_ gnuteardrops announced their website for publishing Monero designs. https://monero.graphics/
17:04:20 <carrington[m]_ Yes I saw that there was some giant translation PR, that's good to see
17:04:51 <carrington[m]_ I assume ErCiccione is behind the haveno website, don't think they are here
17:06:03 <carrington[m]_ We can move onto CCS proposals/updates if no one wants to highlight anything else
17:06:45 <carrington[m]_ First up is monero-guides  proposal to create a video guide series
17:06:48 <carrington[m]_ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/271
17:07:24 <Rucknium[m]_ OSPEAD Update: Work continues. I am getting feedback on how to present the "dry run" results from carrington  and jberman  . Follow the progress here if you dare: https://github.com/Rucknium/OSPEAD
17:08:00 <carrington[m]_ It doesn't look like they are here. My own opinion is that the first guide video they made was great so a series sounds good. I'm less sure on if the price is a fair level because I am not involved in video production.
17:08:34 <carrington[m]_ Rucknium: sorry for the delay getting back to you, other stuff has gotten in the way recently
17:08:35 <netrik182_ Can't comment on prices neither 
17:09:20 <Rucknium[m]_ carrington: No problem at all. In parallel I am working on BCH stuff, so there is no real delay.
17:10:15 <carrington[m]_ If no one has any comments on monero-guides proposal for now we can move on
17:10:53 <midipoet_ we should try and comment on the proposal/MR at least (if at minimum for feedback?)
17:10:53 <carrington[m]_ I probably should have shilled this meeting more widely to get proposers to be here to answer questions. Sorry about that.
17:11:01 <carrington[m]_ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/273
17:11:09 <netrik182_ Fwiw I think a video series would be nice
17:11:58 <carrington[m]_ Yes please drop a comment on any proposals you have opinions on (applies to everyone)
17:12:06 <carrington[m]_ On the MRs
17:12:15 <Rucknium[m]_ I think the monero-guides proposal should go to funding stage, personally.
17:13:03 <carrington[m]_ Next is Pluja's proposal for Monero education content
17:13:17 <carrington[m]_ (I can't find their matrix handle to tag them)
17:13:33 <msvb-mob_ I looked and tried to find them as well, but failed.
17:13:49 <msvb-mob_ It's a really cool idea, wish we could ask questions.
17:14:13 <carrington[m]_ My own opinion, which I'll add as a comment, is that extra education content would be most effective if it was worked into updates to getmonero.org
17:14:44 <msvb-mob_ Or monerodocs.org.
17:14:57 <msvb-mob_ Or pluja is correct to make it its own specific area.
17:15:26 <carrington[m]_ Yeah I'm not sure which direction is best, but I'll suggest it as something for them to consider
17:15:57 <carrington[m]_ Next is netrik182  's proposal for translation coordination
17:15:59 <carrington[m]_ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/275
17:16:52 <carrington[m]_ Would you like to summarize your plans netrik182 ?
17:16:53 <netrik182_ Yeah, first month is completed and I would like to keep managing translations
17:17:12 <netrik182_ I'm open to any questions you may have
17:17:17 <netrik182_ Sure carrington 
17:17:42 <carrington[m]_ I'm glad that your first month didn't put you off and that it seems lots of successful translation was completed
17:18:01 <netrik182_ Plan is to keep managing contributors and all resources mentioned in the proposal
17:18:37 <carrington[m]_ Do you feel there is a decent number/variety of translators to keep up with changes to the software?
17:18:54 <netrik182_ I personally interested in advancing getmonero.org translation 
17:19:36 <netrik182_ The Russian, Spanish and Brazilian Portuguese are most active 
17:19:57 <netrik182_ GUI is 100% translated in those languages 
17:20:09 <netrik182_ German as well iirc
17:20:43 <midipoet_ that's pretty cool
17:20:55 <netrik182_ Dutch is pretty much active too
17:21:07 <carrington[m]_ I think it is important to emphasise translator recruitment (if that is possible) in languages used in oppressive regimes with low English usage
17:21:30 <carrington[m]_ Of course you can't make volunteers appear, but that is where XMR is most needed
17:22:09 <netrik182_ https://translate.getmonero.org/engage/monero/
17:22:44 <carrington[m]_ That is great to hear, and that site is very informative. Hopefully things will not get too crazy in the run up to the network upgrade.
17:22:53 <netrik182_ Yeah, I am really interested in getmonero.org analytics
17:22:56 <msvb-mob_ There are many interesting interfaces where a manager could make a difference, for example engaging the PT region if we're doing Monerokon in Lisboa.
17:23:12 <msvb-mob_ ...which seems to already be quite healthy.
17:23:29 <netrik182_ We would benefit knowing where people connect from
17:23:57 <netrik182_ And which pages are most visited for example 
17:25:03 <carrington[m]_ Such metrics would also interesting to people in #monero-ux:monero I think.social I think
17:25:03 <carrington[m]_ Ill move us on to the TNABC proposal from msvb-mob as time is limited I think
17:25:17 <carrington[m]_ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/274
17:25:22 <msvb-mob_ Yes, dankon thanks.
17:25:43 <msvb-mob_ The proposal is quite comprehensive, most things are described well there.
17:25:57 <carrington[m]_ This proposal isn't visible in the "Ideas" frontend section of the CCS btw
17:25:57 <Rucknium[m]_ If people are using Tor or VPNs, then source of connection  to the website doesn't tell much.
17:26:06 <msvb-mob_ The tldr byline is 'we sideload a Monero component into a interesting BTC event by giving out free wallets.'
17:26:09 <sgp__ I think this conference is a good way to get in front of many people's faces
17:26:38 <msvb-mob_ carrington[m]: Can you please suggest what I should do to correct the problem with the 'Ideas' missing?
17:26:45 <rottenstonks_ carrington[m]: yes, not visible in the ideas section.
17:26:55 <rottenstonks_ perhaps luigi1111 is the best suited to assess what is wrong with the draft.
17:27:18 <msvb-mob_ I'm totally lost how to fix the problem with lack of 'Ideas.'
17:27:23 <carrington[m]_ I'm not really sure why that has happened, but I can look into it later if no one else knows
17:27:46 <midipoet_ i think the efforts at TNABC are a good idea. as long as we aren't parading around shouting "monero is the new/better/real bitcoin" to everyone, and rather subtly reminding/informing them of the benefits, i don't think there is much overarching risk.
17:28:30 <rottenstonks_ msvb-mob: just in case, carrington[m] is referring to the proposal not showing up in this specific section of the CCS site. https://ccs.getmonero.org/ideas/
17:28:31 <netrik182_ Rucknium: true. But knowing which pages they navigate most can be useful to translate first regardless the language 
17:28:40 <sgp__ midipoet: While true, there will be other coins there too so there's no way we can possibly be worse than all the other coins out there, lol
17:28:44 <msvb-mob_ We chose staff members wisely to avoid the circus drama midipoet, because we have the same concern. It's a first year experimental interruption (to BTC.)
17:28:54 <carrington[m]_ As I said in the MR, I think giving BTC and XMR equal prominence in the banner would help with this. If it already created then I guess it is too late
17:28:58 <rottenstonks_ usually it is something to do with the content or the way the proposal gets submitted. something must be wrong. problem is, i don't know what that could be.
17:29:10 <midipoet_ sgp_: well, that is probably true.
17:29:26 <msvb-mob_ I understand the concept rottenstonks, just was hoping someone would spoon me the solution, oh well.
17:30:31 <midipoet_ front-matter?
17:30:42 <rottenstonks_ there are still a few things being deliberated in the comments section of that CCS MR, for what it is worth. everyone should feel welcome to reply and chime in there. https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/274
17:30:55 <netrik182_ msvb-mob: you need to edit lines 9 and 13 to read only the numbers 51 and 25
17:30:56 <msvb-mob_ carrington[m]: One banner is created but we were just awarded a lot more graphic real estate to use for such things as your and anhdres' sisterhood concept.
17:31:13 <netrik182_ You can't have 66%... and such characters
17:31:22 <msvb-mob_ Thank you netrik182!
17:31:42 <msvb-mob_ We got the Golden package, no joke that's what it is really called.
17:32:02 <msvb-mob_ Extra 7.2 Metres of graphic display just like the commercial folks love to paste with logos.
17:32:11 <netrik182_ I would remove " " from the title and fix the date to December 2, 2021
17:32:22 <netrik182_ Look at mine to have an idea
17:33:08 <msvb-mob_ We'll probably advance the proposal before there is another meeting, in case anyone is particularly interested in influencing events we do now is the time to speak.
17:33:30 <rottenstonks_ Advance the proposal?
17:33:40 <rottenstonks_ There are a handful of comments you have not replied to, made by me.
17:33:44 <rottenstonks_ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/274
17:33:57 <rottenstonks_ One or two I tagged you, still no response to this day.
17:33:57 <netrik182_ Those instructions are in https://ccs.getmonero.org/how-to-ccs/
17:34:19 <carrington[m]_ Rotten, it looks like either your messages aren't getting through or you are still banned from the server
17:34:27 <msvb-mob_ Maybe the question fell through the cracks rottenstocks, can you express it here clearly?
17:34:34 <msvb-mob_ And I'll answer if you want one from me personally.
17:34:37 <rottenstonks_ No. It is in the merge request.
17:34:45 <sgp__ The proposal pays the travel costs of 2 people (Michael + Alicia) and Monero tyvek wallets essentially
17:34:46 <rottenstonks_ Please follow up in there.
17:34:49 <msvb-mob_ Ill look again.
17:34:51 <carrington[m]_ Wasn't it a temporary ban? Idk, but we should move on to the next proposal
17:35:05 <netrik182_ They only show on IRC for me (monerologs.net)
17:35:27 <carrington[m]_ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/276
17:35:30 <rottenstonks_ Yeah, the bot banned me on Matrix, not IRC. Sorry, Matrix folks. Not my decision to have done that. :)
17:36:45 <carrington[m]_ This is the draft proposal for the Monerokon 2022 event. There is a Monerokon -specific meeting right after this at 18:00 UTC in #monero-events:monero.social 
17:37:18 <carrington[m]_ I think we can keep most discussion for that meeting, unless someone here cannot make that meeting and would like to comment?
17:38:10 <midipoet_ yeah, i would like to say that i am not fond of the idea of adding all the speaker and travel costs into that CCS. 
17:38:33 <midipoet_ and maybe that is something we should discuss here (as opposed to the planning meeting)
17:38:41 <netrik182_ I'll try to attend the next meetting carrington 
17:39:29 <midipoet_ the main reason is that i don't think its good to over-budget for the event costs AND overbudget/estimate for the travel/volunteer costs - especially in an evolving covid situation
17:40:14 <midipoet_ and i especially don't like the idea of creating a milestone for the travel/volunteer costs - as that has price fluctuation risk
17:40:22 <carrington[m]_ My issue is I don't know the scale of such a second proposal, so it's unclear to me if it's realistic to make up the difference by reducing the quoted costs for the first proposal
17:40:44 <sgp__ midipoet: Conversely though, under budgeting could be really really bad like it was last time
17:41:23 <midipoet_ carrington[m]: i think that is fair, so we can perhaps guesstimate what that CCS-2 would like. i know sgp threw out a very rough estimate of €1000 per person attending (whether speaker or volunteer). so if we imagine 20 speakers and 5 volunteers?
17:42:02 <midipoet_ sgp_: this is very true. but the two PMs that did that budget (that's there day job pretty much), and they were very keen not to have that happen (under-budget)
17:43:00 <carrington[m]_ Well in that estimate the second proposal is half the size of the first 
17:43:03 <carrington[m]_ Roughly
17:43:07 <midipoet_ however, i am fairly certain that there is near 10k we can save off the first CCS (as we pay invoices/cut costs/make decisions, etc)
17:43:15 <midipoet_ so it would be less again.
17:43:32 <sgp__ So the second proposal estimate is what, $20k?
17:43:38 <sgp__ Just rough idea
17:43:44 <midipoet_ sgp_: roughly, sure
17:43:55 <midipoet_ (i would hope less)
17:44:35 <sgp__ I'd rather you just tack that on to the first one tbh :)
17:44:36 <carrington[m]_ I don't really see the complaint with having a second proposal. If donors don't want to support volunteer costs, that is sad for the volunteers but it doesn't necessarily mess everything up
17:44:51 <rottenstonks_ sgp_: +1
17:45:30 <rottenstonks_ if fear for volatility, add a buffer for the estimated expenses. milestones are there for a reason. set one for the most important matters and a second one for speakers & volunteers costs.
17:46:07 <midipoet_ rottenstonks: i don't want to do a buffer - especially as we are in a relatively hostile market for XMR 
17:46:14 <midipoet_ imagine is Kraken delisted from Europe/US?
17:46:23 <midipoet_ what would happen to price?
17:46:38 <carrington[m]_ But I'm also not against having one larger request with rollover into other Monerokons
17:46:41 <rottenstonks_ i don't know and that is a tangent.
17:47:06 <midipoet_ i don't see why splitting the CCS into two is such a bad idea 
17:47:06 <carrington[m]_ Anyway we should try and fit in the newest proposal and open ideas time
17:47:12 <rottenstonks_ if there's extra money it could get sent back to general fund.
17:47:20 <carrington[m]_ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/277
17:47:33 <carrington[m]_ Here is elizabeth 's proposal for ETH-XMR atomic swaps
17:47:41 <rottenstonks_ elizabeth[m]: got any comments on this?
17:48:06 <midipoet_ rottenstonks: sure, we can do that. but then we are probably going to have near a €100k proposal (if you include the safety/price/fluctuation buffer)
17:48:56 <carrington[m]_ (Sorry I am moving through these quickly, but we have an unusually large number of proposals and conversations can of course continue here afterwards or in the CCS comment sections)
17:49:11 <msvb-mob_ This will result in flames at me, but I want to say what incredible venue options are up for discussion in the next hour, that it indirectly proves staff planning (and the CCS for it) are quite active and competent.
17:49:15 <rottenstonks_ i personally prefer a single proposal and break it into two or three milestones. apparently, i am not the only one consdering this.
17:49:25 <Rucknium[m]_ ETH<_XMR atomic swaps are very important. Monero continues to face threats of delisting in centralized exchanges. And ETH has "DeFi".
17:49:41 <Rucknium[m]_ Or DEXes, rather. DeFi too, I guess.
17:50:07 <netrik182_ I see no problem of two proposals if the need be midipoet 
17:51:01 <msvb-mob_ Pretty cool if elizabeth[m] appears, we have not heard from her before have we?
17:51:07 <msvb-mob_ Or him.
17:51:15 <elizabeth[m]_ I'm here for any questions 
17:52:13 <carrington[m]_ It would be incredible if easy atomic swaps were possible for users into multiple coins. I see that Farcaster (XMR-BTC swaps) is nearly ready for release
17:52:46 <msvb-mob_ elizzabeth[m]: You're supposed to copy the entire (except for metadata) text in the MR description. So we can read and review easily.
17:52:48 <monero-guides[m]_ what exactly is the incentive to swap xmr with eth? woudn't it be very expensive?
17:52:54 <midipoet_ yeah, i think nearly everybody supports atomic swaps
17:53:30 <netrik182_ For the record: I support elizabeth's proposal 
17:53:35 <Rucknium[m]_ elizabeth: Practically speaking, at the end of this CCS, how easy will it be for a noobish user to execute a swap, all things considered?
17:53:42 <carrington[m]_ It gives XMR holders access to the ETH ecosystem
17:53:53 <carrington[m]_ Without trusted third parties
17:54:13 <elizabeth[m]_ monero-guides[m]: it would be with the current implementation, but there are a few milestones in the proposal that should greater reduce the costs. I'd also like to deploy it on L2 as well as L1 
17:54:23 <sgp__ This proposal should be moved yesterday
17:54:27 <elizabeth[m]_ * it would be with the current implementation, but there are a few milestones in the proposal that should greatly reduce the costs. I'd also like to deploy it on L2 as well as L1 
17:54:30 <Rucknium[m]_ monero-guides: Users are going to swap to the cheap EVM-compatible chain, smartBCH 😉
17:55:26 <msvb-mob_ I'm trying to read it because it sounds totally interesting sgp_ elizabeth[m], and I'm looking here but not finding it https://repo.getmonero.org/noot/ccs-proposals/
17:55:38 <monero-guides[m]_ if it can be used in other chains, is it simple?
17:55:40 <elizabeth[m]_ * it would be with the current implementation, but there are a few milestones in the proposal that should greatly reduce the costs. I'd also like it to be deployed on L2 as well as L1 
17:56:06 <elizabeth[m]_ msvb-mob: it's here https://repo.getmonero.org/noot/ccs-proposals/-/blob/master/noot-eth-xmr-atomic-swap.md
17:56:29 <sgp__ elizabeth[m]: By L2 do you mean Arbitrum?
17:56:36 <elizabeth[m]_ monero-guides[m]: yes, it should be simple to deploy on any EVM based chain
17:56:59 <msvb-mob_ Thanks elizabeth[m], found it now.
17:57:09 <monero-guides[m]_ it would be nice if the finished product had wrapping and a bow for use else where
17:57:18 <monero-guides[m]_ in that case
17:57:41 <elizabeth[m]_ sgp_: probably any L2 :p 
17:58:00 <elizabeth[m]_ monero-guides[m]: do you mean steps for easily deploying it? 
17:58:27 <monero-guides[m]_ yep, an option for those who don't care about the eth ecosystem
17:59:28 <elizabeth[m]_ yep, I can add steps/documentation for that
17:59:54 <msvb-mob_ Totally off topic, but this is the kind of expert information perfect for Monerokon. And noot/elizabeth is not on carrington[m]'s cryptpad.
18:00:36 <carrington[m]_ There is a meeting in #monero-events:monero.social  starting now, so I will end the meeting for the purposes of logs here. 
18:01:09 <carrington[m]_ The list of potential speakers is something I need to work on more (others are welcome to add to it or reach out)
18:01:25 <carrington[m]_ I'll make sure to add comments on each proposal and I encourage others to do the same
18:01:31 <carrington[m]_ Thanks for coming all!
