### ISSUE TITLE
[Action Required] Defcon Supplies for Monero / Cryptocurrency Village

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/meta#718]
Our contract for storage in Las Vegas for the Monero / Cryptocurrency Village supplies ends on **July 31st.**

Thus, we need to make a rapid, sensible decision on what to do with supplies. There is no Monero Village or Cryptocurrency Village this year, and there likely will not be a village in future years. While sad, the Monero Event Workgroup has focused on the more-important Monero Konferenco, and Monero Talk has focused on Monerotopia.

As I see it, here are some of the possible options. Not all of them are available unless someone steps up.

1. We let Monero Talk take what they want for Monerotopia
2. We let a Monero community member pick up the supplies and hold them for storage
3. We let the Zcash Foundation take what they want for Zcon3, live in Vegas August 7-9
4. We let another Defcon village have the stuff they want
5. We keep paying the storage contract for $150/mo

### Option 1: We let Monero Talk take what they want for Monerotopia

This isn't exclusive. We can offer to let them take what they want and leave or discard the rest.

I think if they want anything, this is the best first option. Monerotopia is a Monero-related event.

### Option 2: We let a Monero community member pick up the supplies and hold them for storage

This is the second best option. If someone has a house in the Vegas area with extra room in their basement/attic, please let us know! This will allow us to extend the decision process. They could even sell the parts slowly if the community desires.

This community member could in theory secure alternative self-storage options for cheaper than Option 5, but this isn't a real option unless a volunteer steps up.

If a Monero community member lives *near* Vegas (within a drive) and is willing to help, then please let us know! It could be very helpful to help coordinate options. Paying for your travel and gas is cheaper than an annual storage contract!

### Option 3: We let the Zcash Foundation take what they want for Zcon3, live in Vegas August 7-9

This isn't exclusive. I have no idea if they want anything. We can offer to let them take what they want and leave or discard the rest.

### Option 4: We let another Defcon village have the stuff they want

This isn't exclusive. We can offer to let them take what they want and leave or discard the rest. I have no idea if any villages want anything since I haven't asked.

### Option 5: We keep paying the storage contract for $150/mo ($1,800/yr)

We have the option of paying monthly, or even prorated for the first month. I think this is foolish if we aren't going to use the equipment though.

---

List of supplies: 

Quantity | Description | Notes
-- | -- | --
2 | Wireless mic receivers |  
1 | Xenyx 1202 FX behringer | No proprietary power cable
1 | Mackie Mix 8 8 Channel Mixer |  
1 | Epson projector |  
1 | Case for Epson projector |  
10 | AA batteries | approx count
10 | AAA batteries | approx count
1 | Battery case and tester |  
1 | LED flashlight |  
3 | International to US power adapters |  
2 | LED lights, batteries, and charger | no power cables, no stands
1 | Pack of index cards | about 100 cards total
5 | Glue guns | approx count
50 | Sticks of glue gun glue | approx count
24 | Cheap pens | approx count
1 | Hard plastic pencil case |  
1 | Rockville power gig RPG-122K speakers w/power cable |  
1 | 6 foot HDMI cable |  
1 | 6 port power strip |  
2 | Cryptocurrency Village banners | reusable for future years as "cryptocurrency village"
1 | Vertical stand whiteboard | only free-stands from ground, missing pole to prop up higher
1 | Compact dolly |  
4 | Circular lights (power only) |  
2 | ~66 inch tall tripods with standard screw port | no phone adapters
1 | 10 foot RCA red/white to 3.5 mm |  
1 | Gerber multitool |  
2 | 32" TCL TVs |  
1 | Minko plinko board | Very large; needs to fit diagonal in U-Haul van
1 | Sterilite 27 Gal. Industrial Tote Yellow Lily | Outside Dimensions: 30 1/2" x 20 5/8" x 15 1/4"; Interior   Dimensions at bottom: 24 3/4" x 15 3/4" x 14 3/8"
1 | Igloo 48 qt. Laguna Ice Chest Cooler, Red | 25.71" x 14.12" x 14.25" Inches; no drain
  | Various leftover badges from Michael |  

---

Contact info:

* Email: info@magicgrants.org
* Signal: 708-252-3261
* Matrix: @sgp_:monero.social

**Comment by kayabaNerve** [comment]
Is Monero Talk even in a position to do so?

Regardless, I'm most in favor of 1/2/4, if this is meant to solicit opinions, in that order. Monero conference, an unknown Monero future, before finally keeping it within Defcon.

**Comment by michaesc** [comment]
Hi @SamsungGalaxyPlayer ,

Please correct the phrase:

>There is no Monero Village or Cryptocurrency Village this year, and there likely will not be a village in future years.
>

It can be corrected to either:

>There is no Monero Village this year, and there will not likely ever be a Monero Village at Defcon.
>

...or:

>There is no Monero Village this year, and the Cryptocurrency Village storage area is funded by a non Monero group. There will likely be Cryptocurrency Village appearances every year to come.
>

If this is confusing or not important, you could just erase text referring to appearances of Monero Village and Cryptocurrency Village. It's wrong the way it's written now though.

### Actions

By the way, I think all the options you refer to are good ones, in any given order. Dankon very much for developing the options to resolve the problem.

### Quality

Some of the equipment is in new condition but of such poor quality that it's worthless. For example all the hotglue application tools were so carelessly purchased that they are in new condition and suitable for worthless disposal.

### Handling

I can offer some limited handling of the storage contents using a rental truck in Vegas for our Cryptocurrency Village appearance at Defcon 2022 in the vendor area.

The problem is that the on site truck rental is for a single day in August, so the 31 July storage expiration would need to be extended one month.

Just tell me if it's desirable that I enter the area and photograph, clean, dispose, or otherwise handle the contents.

Thanks,
Michael

**Comment by SamsungGalaxyPlayer** [comment]
### Update: Monero Talk has indicated that they do not want anything.

So option 1 is off the table.

**Comment by kowalabearhugs** [comment]
Since option 1 is now off the table, I support options 2 and 4. 

The supplies should go towards projects/conferences that embrace FOSS and/or FOSH.

**Comment by johnr365** [comment]
@SamsungGalaxyPlayer - since the post, have you had anyone from the Monero community, in Vegas, mention that they'd be interested in picking up the supplies?

Given #1 is off the table, then 2, 3 and 4 seem to make most sense. $1800 per year on storage doesn't make sense if there isn't a clear future point the equipment will be used.
