### ISSUE TITLE
Add description, website, and/or topics for all Monero Project repo's

### ISSUE THREAD

**Issue by anonimal** [monero-project/meta#78]
- [kovri-site](https://github.com/monero-project/kovri-site) and [kovri-docs](https://github.com/monero-project/kovri-site) do not have description or website or topics listed. 
- [kovri](https://github.com/monero-project/kovri) does not have a website or topics listed
- *none* of the Monero repos have topics listed
- AFAICT, only the monero repo has a website listed

Topics were introduced here https://github.com/blog/2309-introducing-topics

**Comment by anonimal** [comment]
https://help.github.com/articles/classifying-your-repository-with-topics/

**Comment by michaesc** [comment]
@anonimal Where is the 'description' found on the [Kovri repository](https://github.com/monero-project/kovri/)? Where should it be possible to view the 'website' information?

I'm asking in order to specify relevant information on the hardware wallet repository, that is consistent with other neighbors in github.com/monero-project. Would be nice to be consistent no?

### Topics

Should there be a set of **common topics** across the board plus unique ones to each repository? If so:

- monero
- cryptocurrency
- blockchain
- privacy
- finance

...what do you think about these common topics?

**Comment by anonimal** [comment]
>Where is the 'description' found on the Kovri repository?

In the code tab, `The Kovri I2P Router Project`.

>Where should it be possible to view the 'website' information?

An [example](https://github.com/weidai11/cryptopp).

>...what do you think about these common topics?

Great idea, let's do it.

**Comment by HardenedSteel** [comment]
this issue can be closed
